/**
*  @file znp_app_utils.h
*
*  @brief  public methods for znp_app_utils.c
*
* $Rev: 1.0 $
* $Author: czl $
* $Date: 2012-11-04 $
*
* YOU ACKNOWLEDGE AND AGREE THAT THE SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS?WITHOUT WARRANTY 
* OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY, 
* TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT SHALL TEXAS INSTRUMENTS 
* OR ITS LICENSORS BE LIABLE OR OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION, 
* BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT DAMAGES OR EXPENSES
* INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL, INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, 
* LOST PROFITS OR LOST DATA, COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY 
* CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF), OR OTHER SIMILAR COSTS.
*/
#ifndef ZNP_APP_UTILS_H_INCLUDED
#define ZNP_APP_UTILS_H_INCLUDED

extern signed int startZnp(unsigned char deviceType);

//STATES for state machine
#define STATE_IDLE                              1
#define STATE_ZNP_STARTUP                       2
#define STATE_DISPLAY_NETWORK_INFORMATION       3
#define STATE_SEND_INFO_MESSAGE                 4

#endif

/* end of file znp_app_utils.h */